apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops  
spec:
  replicas: 2
  revisionHistoryLimit: 10  
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 2  
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19.0 
        name: nginx
        resources:
          limits:
            cpu: 0.5
            memory: 128Mi
          requests:
            cpu: 0.3
            memory: 64Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5 
          failureThreshold: 3         
