apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None # Deve ser como NONE para não pegar ip e funcionar literalmente como headless
  selector:
    app: nginx
---