apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxgiro
  name: nginxgiro
spec:
  containers:
  - image: nginx
    name: nginxgiro
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
