events { }

http {
  server {
    listen 80;
    listen 443 ssl;

    ssl_certificate /etc/nginx/tls/certificado.crt;
    ssl_certificate_key /etc/nginx/tls/chave-privada.key;

    location / {
      return 200 'Fala cole!!\n';
      add_header Content-Type text/plain;
    } 
  }
}

## a identação pode ocasionar erro no processo de compilação.