apiVersion: v1
kind: Pod
metadata:
  name: wayner-pod
spec:
  containers:
    - name: wayner-container
      image: nginx:latest
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: giropops-test
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: giropops-test
            key: password
      ports:
        - containerPort: 80